definitions:
  auth.userToken:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/domain.User'
    type: object
  domain.CompletedTaskPoint:
    properties:
      createdAt:
        type: string
      gameId:
        type: string
      photo:
        type: string
      playerId:
        type: string
      pointId:
        type: string
      score:
        type: integer
    type: object
  domain.Coordinate:
    properties:
      lat:
        type: number
      lon:
        type: number
    type: object
  domain.CreateUser:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  domain.Game:
    properties:
      activePoll:
        $ref: '#/definitions/domain.Poll'
      admin:
        $ref: '#/definitions/domain.User'
      completedTaskPoints:
        items:
          $ref: '#/definitions/domain.CompletedTaskPoint'
        type: array
      createdAt:
        type: string
      finishedAt:
        type: string
      id:
        type: string
      players:
        items:
          $ref: '#/definitions/domain.Player'
        type: array
      route:
        $ref: '#/definitions/domain.Route'
      seed:
        type: string
      state:
        $ref: '#/definitions/domain.GameState'
    type: object
  domain.GameState:
    enum:
    - lobby
    - game
    - poll
    - finished
    type: string
    x-enum-varnames:
    - GameStateLobby
    - GameStateGame
    - GameStatePoll
    - GameStateFinished
  domain.PatchUser:
    properties:
      name:
        type: string
      styles:
        $ref: '#/definitions/domain.UserStyles'
      username:
        type: string
    type: object
  domain.Player:
    properties:
      gameId:
        type: string
      location:
        $ref: '#/definitions/domain.Coordinate'
      role:
        $ref: '#/definitions/domain.PlayerRole'
      score:
        type: integer
      user:
        $ref: '#/definitions/domain.User'
    type: object
  domain.PlayerRole:
    enum:
    - runner
    - catcher
    type: string
    x-enum-varnames:
    - PlayerRoleRunner
    - PlayerRoleCatcher
  domain.Poll:
    properties:
      createdAt:
        type: string
      data:
        $ref: '#/definitions/domain.PollData'
      duration:
        type: integer
      finishedAt:
        type: string
      gameId:
        type: string
      id:
        type: string
      result:
        $ref: '#/definitions/domain.PollResult'
      state:
        $ref: '#/definitions/domain.PollState'
      type:
        $ref: '#/definitions/domain.PollType'
      votes:
        items:
          $ref: '#/definitions/domain.Vote'
        type: array
    type: object
  domain.PollData:
    properties:
      finishGame:
        $ref: '#/definitions/domain.PollDataFinishGame'
      pause:
        $ref: '#/definitions/domain.PollDataPause'
      playerCatch:
        $ref: '#/definitions/domain.PollDataPlayerCatch'
      taskComplete:
        $ref: '#/definitions/domain.PollDataTaskComplete'
    type: object
  domain.PollDataFinishGame:
    properties:
      comment:
        type: string
      suggestedBy:
        $ref: '#/definitions/domain.Player'
    type: object
  domain.PollDataPause:
    properties:
      duration:
        type: integer
      pausedBy:
        $ref: '#/definitions/domain.Player'
    type: object
  domain.PollDataPlayerCatch:
    properties:
      catchedBy:
        $ref: '#/definitions/domain.Player'
      photo:
        type: string
      runner:
        $ref: '#/definitions/domain.Player'
    type: object
  domain.PollDataTaskComplete:
    properties:
      photo:
        type: string
      player:
        $ref: '#/definitions/domain.Player'
      task:
        $ref: '#/definitions/domain.TaskPoint'
    type: object
  domain.PollResult:
    properties:
      finishGame:
        $ref: '#/definitions/domain.PollResultFinishGame'
      pause:
        $ref: '#/definitions/domain.PollResultPause'
      playerCatch:
        $ref: '#/definitions/domain.PollResultPlayerCatch'
      taskComplete:
        $ref: '#/definitions/domain.PollResultTaskComplete'
    type: object
  domain.PollResultFinishGame:
    properties:
      approved:
        type: boolean
    type: object
  domain.PollResultPause:
    properties:
      unpausedBy:
        $ref: '#/definitions/domain.Player'
    type: object
  domain.PollResultPlayerCatch:
    properties:
      approved:
        type: boolean
      catcherReward:
        type: integer
      newRunner:
        $ref: '#/definitions/domain.Player'
    type: object
  domain.PollResultTaskComplete:
    properties:
      approved:
        type: boolean
      completedTaskPoint:
        $ref: '#/definitions/domain.CompletedTaskPoint'
    type: object
  domain.PollState:
    enum:
    - active
    - finished
    type: string
    x-enum-varnames:
    - PollStateActive
    - PollStateFinished
  domain.PollType:
    enum:
    - pause
    - taskComplete
    - playerCatch
    - finishGame
    type: string
    x-enum-varnames:
    - PollTypePause
    - PollTypeTaskComplete
    - PollTypePlayerCatch
    - PollTypeFinishGame
  domain.Route:
    properties:
      bought:
        type: boolean
      description:
        type: string
      id:
        type: string
      priceRoubles:
        type: integer
      taskPoints:
        items:
          $ref: '#/definitions/domain.TaskPoint'
        type: array
      title:
        type: string
    type: object
  domain.Style:
    properties:
      bought:
        type: boolean
      id:
        type: string
      priceRoubles:
        type: integer
      style: {}
      title:
        type: string
      type:
        $ref: '#/definitions/domain.StyleType'
    type: object
  domain.StyleType:
    enum:
    - avatar
    type: string
    x-enum-varnames:
    - StyleTypeAvatar
  domain.TaskPoint:
    properties:
      description:
        type: string
      id:
        type: string
      location:
        $ref: '#/definitions/domain.Coordinate'
      score:
        type: integer
      task:
        type: string
      title:
        type: string
    type: object
  domain.User:
    properties:
      id:
        type: string
      name:
        type: string
      styles:
        $ref: '#/definitions/domain.UserStyles'
      username:
        type: string
    type: object
  domain.UserCredentials:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  domain.UserStyles:
    properties:
      avatarId:
        type: string
    type: object
  domain.Vote:
    properties:
      createdAt:
        type: string
      data:
        $ref: '#/definitions/domain.VoteData'
      gameId:
        type: string
      playerId:
        type: string
      pollId:
        type: string
      type:
        $ref: '#/definitions/domain.VoteType'
    type: object
  domain.VoteData:
    properties:
      comment:
        type: string
    type: object
  domain.VoteType:
    enum:
    - unpause
    - taskApprove
    - taskReject
    - playerCatchApprove
    - playerCatchReject
    - finishGameApprove
    - finishGameReject
    type: string
    x-enum-varnames:
    - VoteTypeUnpause
    - VoteTypeTaskApprove
    - VoteTypeTaskReject
    - VoteTypePlayerCatchApprove
    - VoteTypePlayerCatchReject
    - VoteTypeFinishGameApprove
    - VoteTypeFinishGameReject
  image.UploadResponse:
    properties:
      url:
        type: string
    type: object
  style.setAvatarRequest:
    properties:
      styleId:
        type: string
    type: object
info:
  contact: {}
  title: Sightquest server
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.UserCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.userToken'
        "400":
          description: Bad Request
      summary: Login user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.userToken'
        "400":
          description: Bad Request
      summary: Register user
      tags:
      - auth
  /game:
    post:
      consumes:
      - application/json
      parameters:
      - description: Seed for game
        in: query
        name: seed
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Game'
        "400":
          description: Bad Request
      security:
      - ApiKeyAuth: []
      summary: Create game
      tags:
      - game
  /game/id/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Game'
        "400":
          description: Bad Request
      security:
      - ApiKeyAuth: []
      summary: Get game by id
      tags:
      - game
  /game/latest:
    get:
      consumes:
      - application/json
      parameters:
      - description: Number of games to return
        in: query
        name: limit
        required: true
        type: integer
      - description: Game state
        enum:
        - lobby
        - game
        - poll
        - finished
        in: query
        name: state
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Game'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
      security:
      - ApiKeyAuth: []
      summary: Get last N games for a player
      tags:
      - game
  /images/upload/by_file:
    post:
      consumes:
      - application/json
      parameters:
      - description: Image data
        in: formData
        name: file
        required: true
        type: file
      - description: Directory in s3 storage
        in: query
        name: dir
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: A url to the stored image
          schema:
            $ref: '#/definitions/image.UploadResponse'
        "400":
          description: Parsing error
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Upload file to s3
      tags:
      - images
  /route:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Route'
            type: array
        "400":
          description: Bad Request
      summary: Get all routes
      tags:
      - route
  /route/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Route ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Route'
        "400":
          description: Bad Request
        "404":
          description: Not Found
      summary: Get route by ID
      tags:
      - route
  /route/{id}/buy:
    post:
      consumes:
      - application/json
      parameters:
      - description: Route ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      security:
      - ApiKeyAuth: []
      summary: Buy route
      tags:
      - route
  /styles:
    get:
      consumes:
      - application/json
      parameters:
      - description: Style type filter
        in: query
        name: type
        type: string
      - description: Bought filter
        in: query
        name: bought
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Style'
            type: array
        "400":
          description: Bad Request
      security:
      - ApiKeyAuth: []
      summary: Get available styles
      tags:
      - style
  /styles/id/{id}/buy:
    post:
      consumes:
      - application/json
      parameters:
      - description: Style ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      security:
      - ApiKeyAuth: []
      summary: Buy style
      tags:
      - style
  /styles/me/avatar:
    post:
      consumes:
      - application/json
      parameters:
      - description: Style ID
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/style.setAvatarRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
      security:
      - ApiKeyAuth: []
      summary: Set avatar style
      tags:
      - style
  /user/me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
      security:
      - ApiKeyAuth: []
      summary: Get me
      tags:
      - user
    patch:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.PatchUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
      security:
      - ApiKeyAuth: []
      summary: Patch me
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-API-Token
    type: apiKey
swagger: "2.0"
