definitions:
  auth.userToken:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/domain.User'
    type: object
  domain.Coordinate:
    properties:
      lat:
        type: number
      lon:
        type: number
    type: object
  domain.CreateUser:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  domain.Game:
    properties:
      admin:
        $ref: '#/definitions/domain.User'
      createdAt:
        type: string
      finishedAt:
        type: string
      id:
        type: string
      players:
        items:
          $ref: '#/definitions/domain.Player'
        type: array
      state:
        $ref: '#/definitions/domain.GameState'
    type: object
  domain.GameState:
    enum:
    - lobby
    - game
    - poll
    - finished
    type: string
    x-enum-varnames:
    - GameStateLobby
    - GameStateGame
    - GameStatePoll
    - GameStateFinished
  domain.PatchUser:
    properties:
      avatar:
        type: string
      background:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
  domain.Player:
    properties:
      gameId:
        type: string
      location:
        $ref: '#/definitions/domain.Coordinate'
      role:
        $ref: '#/definitions/domain.PlayerRole'
      score:
        type: integer
      user:
        $ref: '#/definitions/domain.User'
    type: object
  domain.PlayerRole:
    enum:
    - runner
    - catcher
    type: string
    x-enum-varnames:
    - PlayerRoleRunner
    - PlayerRoleCatcher
  domain.Route:
    properties:
      description:
        type: string
      id:
        type: string
      priceRoubles:
        type: integer
      taskPoints:
        items:
          $ref: '#/definitions/domain.TaskPoint'
        type: array
      title:
        type: string
    type: object
  domain.TaskPoint:
    properties:
      description:
        type: string
      id:
        type: string
      location:
        $ref: '#/definitions/domain.Coordinate'
      score:
        type: integer
      task:
        type: string
      title:
        type: string
    type: object
  domain.User:
    properties:
      avatar:
        type: string
      background:
        type: string
      id:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
  domain.UserCredentials:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  title: Sightquest server
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.UserCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.userToken'
        "400":
          description: Bad Request
      summary: Login user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.userToken'
        "400":
          description: Bad Request
      summary: Register user
      tags:
      - auth
  /game:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Game'
        "400":
          description: Bad Request
      security:
      - ApiKeyAuth: []
      summary: Create game
      tags:
      - game
  /game/id/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Game'
        "400":
          description: Bad Request
      security:
      - ApiKeyAuth: []
      summary: Get game by id
      tags:
      - game
  /game/latest:
    get:
      consumes:
      - application/json
      parameters:
      - description: Number of games to return
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Game'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
      security:
      - ApiKeyAuth: []
      summary: Get last N games for a player
      tags:
      - game
  /route:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Route'
            type: array
        "400":
          description: Bad Request
      summary: Get all routes
      tags:
      - routes
  /route/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Route ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Route'
        "400":
          description: Bad Request
        "404":
          description: Not Found
      summary: Get route by ID
      tags:
      - routes
  /user/me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
      security:
      - ApiKeyAuth: []
      summary: Get me
      tags:
      - users
    patch:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.PatchUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
      security:
      - ApiKeyAuth: []
      summary: Patch me
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-API-Token
    type: apiKey
swagger: "2.0"
