ALTER TABLE "user"
ADD COLUMN IF NOT EXISTS "avatar" text NOT NULL DEFAULT '';

ALTER TABLE "user"
ADD COLUMN IF NOT EXISTS "background" text NOT NULL DEFAULT '';

ALTER TABLE "user"
DROP COLUMN IF EXISTS "styles";

DROP TABLE IF EXISTS "user_style";
DROP TABLE IF EXISTS "style";
