name: deploy-client

on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Deploy to DEV/PROD
        type: choice
        options: [DEV, PROD]

jobs:
    pass_stage:
        name: Skip
        runs-on: ubuntu-latest
        steps:
            - name: Skip
              run: echo "Finished..."