name: deploy-server

on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Deploy to DEV/PROD
        type: choice
        options: [DEV, PROD]

jobs:
  ci:
    uses: ./.github/workflows/ci-server.yaml

  deploy:
    uses: shampsdev/cicd-pipelines/.github/workflows/deploy.yaml@main
    needs: [ci]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    secrets: inherit
    with:
      dockerfile_path: 'server'
      context_path: 'server'
      image_name: 'sightquest-server'
      environment: ${{ github.event.inputs.environment }}
      secret-service-hash: ${{ github.event.inputs.environment == 'PROD' && 'SERVER_SERVICE_HASH' || 'SERVER_SERVICE_HASH_DEV' }}      
