name: deploy-landing

on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Deploy to DEV/PROD
        type: choice
        options: [DEV, PROD]

jobs:
  deploy:
    uses: shampsdev/cicd-pipelines/.github/workflows/deploy.yaml@main
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    secrets: inherit
    with:
      dockerfile_path: 'landing'
      context_path: 'landing'
      image_name: 'sightquest-landing'
      environment: ${{ github.event.inputs.environment }}
      secret-service-hash: ${{ github.event.inputs.environment == 'PROD' && 'LANDING_SERVICE_HASH' || 'LANDING_SERVICE_HASH_DEV' }}      
